### ISSUE TITLE
Error while creating tests for Appwindow.

### ISSUE THREAD

**Issue by bitshadow** [yeoman/yeoman-app#63]
Getting this message `Error: the error {} was thrown, throw an Error :)`

node v0.12.2
npm  v2.7.4

Here is the npm logs for info.
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'test-main' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'pretest-main', 'test-main', 'posttest-main' ]
5 info pretest-main yeoman-app@0.0.0
6 info test-main yeoman-app@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info yeoman-app@0.0.0 Failed to exec test-main script
9 verbose stack Error: yeoman-app@0.0.0 test-main: `mocha spec/main-process`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid yeoman-app@0.0.0
11 verbose cwd /Users/jignesh.kakadiya/projects/self/yeoman-app
12 error Darwin 13.3.0
13 error argv "node" "/usr/local/bin/npm" "run" "test-main"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error yeoman-app@0.0.0 test-main: `mocha spec/main-process`
17 error Exit status 1
18 error Failed at the yeoman-app@0.0.0 test-main script 'mocha spec/main-process'.
18 error This is most likely a problem with the yeoman-app package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     mocha spec/main-process
18 error You can get their info via:
18 error     npm owner ls yeoman-app
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by stefanbuck** [comment]
Amazing, this error message. Sorry... I have no idea what's going on here. Could you raise a PR so I can take a look and debug the code, please. 

Thanks
